service:
  name: probe
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack: # serverless-webpack 관련 설정
    webpackConfig: 'webpack.config.js'
    includeModules: true # apollo-server-lambda와 같이 외부 모듈이 반드시 필요한 경우 설정
    packager: 'npm' # yarn을 사용한다면 yarn으로 설정해주세요.

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-2
  environment: # 환경변수
    NODE_ENV: production

functions:
  graphqlHandler:
    handler: src/handler.graphqlHandler
    events:
      - http:
          method: get
          path: graphql
      - http:
          method: post
          path: graphql
          cors: true
