service:
  name: hello

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-2
  environment: # process.env에 추가될 환경 변수
    NODE_ENV: production
    STAGE: ${opt:stage, self:provider.stage}  
  iamRoleStatements: # Lambda가 dynamodb에 접속할 수 있는 IAM Role 생성
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - { "Fn::GetAtt": ["hello", "Arn"] } # hello는 테이블 리소스 이름

custom:
  stage: ${opt:stage, self:provider.stage}  
  webpack: # serverless-webpack 관련 설정
    webpackConfig: 'webpack.config.js'
    includeModules: true # apollo-server-lambda와 같이 외부 모듈이 반드시 필요한 경우 설정
    packager: 'npm' # yarn을 사용한다면 yarn으로 설정

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

functions:
  # Lambda
  - ${file(resources/lambda-handler.yml)}
  
