service:
  name: probe
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-2
  environment: # 환경변수
    NODE_ENV: production

functions:
  graphqlHandler:
    handler: src/handler.graphqlHandler
    events:
      - http:
          method: get
          path: graphql
      - http:
          method: post
          path: graphql
          cors: true
